
import java.awt.event.KeyEvent;
import java.sql.*;
import java.io.*;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shayan Prakash
 */
public class EmployeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeFrame
     */
    Connection con;
    Statement st;
    PreparedStatement pst;
    ResultSet rs;

    public EmployeeFrame() {
        initComponents();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            //st = con.
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error!!", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        optA = new javax.swing.JRadioButton();
        optB = new javax.swing.JRadioButton();
        optC = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cmbJobs = new javax.swing.JComboBox<>();
        chkGraduate = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCommission = new javax.swing.JTextField();
        cmdAdd = new javax.swing.JButton();
        cmdExit = new javax.swing.JButton();
        cmdView = new javax.swing.JButton();
        cmdEdit = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Empno");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 38, 83, 33);

        txtEmpNo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(txtEmpNo);
        txtEmpNo.setBounds(172, 41, 183, 27);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("EName");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 77, 83, 33);

        txtEName.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(txtEName);
        txtEName.setBounds(172, 80, 183, 27);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Grade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 147, 41, 21);

        optA.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        optA.setText("A");
        optA.setName(""); // NOI18N
        getContentPane().add(optA);
        optA.setBounds(172, 139, 35, 29);

        optB.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        optB.setText("B");
        getContentPane().add(optB);
        optB.setBounds(248, 139, 35, 29);

        optC.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        optC.setText("C");
        getContentPane().add(optC);
        optC.setBounds(320, 139, 35, 29);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Job");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 202, 24, 21);

        cmbJobs.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmbJobs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clerk", "Analyst", "Manager" }));
        getContentPane().add(cmbJobs);
        cmbJobs.setBounds(172, 196, 183, 27);

        chkGraduate.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        chkGraduate.setText("Graduate");
        getContentPane().add(chkGraduate);
        chkGraduate.setBounds(172, 254, 131, 29);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("Salary");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 301, 45, 21);

        txtSalary.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        txtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSalaryKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalaryKeyTyped(evt);
            }
        });
        getContentPane().add(txtSalary);
        txtSalary.setBounds(172, 301, 150, 27);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setText("Commission");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 370, 74, 21);

        txtCommission.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(txtCommission);
        txtCommission.setBounds(170, 360, 150, 27);

        cmdAdd.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmdAdd.setText("Add");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });
        getContentPane().add(cmdAdd);
        cmdAdd.setBounds(390, 270, 78, 29);

        cmdExit.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });
        getContentPane().add(cmdExit);
        cmdExit.setBounds(225, 458, 78, 29);

        cmdView.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmdView.setText("View");
        cmdView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdViewActionPerformed(evt);
            }
        });
        getContentPane().add(cmdView);
        cmdView.setBounds(390, 320, 78, 31);

        cmdEdit.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmdEdit.setText("Edit");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });
        getContentPane().add(cmdEdit);
        cmdEdit.setBounds(390, 370, 80, 29);

        cmdDelete.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cmdDelete.setText("Delete");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(cmdDelete);
        cmdDelete.setBounds(390, 420, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdExitActionPerformed

    private void txtSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSalaryKeyTyped

    private void txtSalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyPressed
        // TODO add your handling code here:
       String grade="", job="";
        float salary = 0.0f, comm = 0.0f;
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            salary = Float.parseFloat(txtSalary.getText());
            System.out.println("Hello" + salary);
            if(salary < 2000 || salary > 7000){
                JOptionPane.showMessageDialog(this, "Salary should be between 2k and 5k","Error!!",JOptionPane.ERROR_MESSAGE);
                txtSalary.requestFocus();
                txtSalary.selectAll();
                return;
            }
            else{
                if(optA.isSelected()){
                    grade="A";
                }
                else if(optB.isSelected()){
                    grade = "B";
                }
                else if(optC.isSelected()){
                    grade = "C";
                }
                job = (String) cmbJobs.getSelectedItem();
                        
                if(job.equalsIgnoreCase("clerk")){
                    comm = 0.05f * salary;
                }
                else if(job.equalsIgnoreCase("analyst")){
                    comm = 0.10f * salary;
                }
                else if(job.equalsIgnoreCase("manager")){
                    comm = 0.15f * salary;
                }
                System.out.println("Commission before grade " + comm);
                if(grade.equalsIgnoreCase("A")){
                    comm = comm + 300;
                }
                else if(grade.equalsIgnoreCase("B")){
                    comm = comm + 200;
                }
                else if(grade.equalsIgnoreCase("C")){
                    comm = comm + 100;
                }
                
            }
        }
        System.out.println(comm);
        txtCommission.setText(String.valueOf(comm));
    }//GEN-LAST:event_txtSalaryKeyPressed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        // TODO add your handling code here:
        int empno;
        String ename, grade="", job, graduate;
        float salary = 0.0f, comm = 0.0f;
        try{
            pst = con.prepareStatement("insert into employees values(?,?,?,?,?,?,?)");
            empno = Integer.parseInt(txtEmpNo.getText());
            ename= txtEName.getText();
            if(optA.isSelected()){
                    grade="A";
                }
                else if(optB.isSelected()){
                    grade = "B";
                }
                else if(optC.isSelected()){
                    grade = "C";
                }
            if(chkGraduate.isSelected()){
                graduate = "Yes";
            }
            else{
                graduate = "No";
            }
            job = (String) cmbJobs.getSelectedItem();
            salary = Float.parseFloat(txtSalary.getText());
            comm = Float.parseFloat(txtCommission.getText());
            pst.setInt(1,empno);
            pst.setString(2,ename);
            pst.setString(3, grade);
            pst.setString(4, job);
            pst.setString(5,graduate);
            pst.setFloat(6, salary);
            pst.setFloat(7, comm);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Employee Added!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Error!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdViewActionPerformed
        // TODO add your handling code here:int empno;
        int empno;
        String ename, grade="", job, graduate;
        float salary = 0.0f, comm = 0.0f;
        try{
            empno= Integer.parseInt(txtEmpNo.getText());
            st = con.createStatement();
            rs = st.executeQuery("select * from employees where empno="+empno);
            if(rs.next() == true){
                txtEName.setText(rs.getString("ename"));
                //grade = "opt"+rs.getString(grade).toUpperCase();
                //System.out.print(grade)
                grade = rs.getString("grade");
                if(grade.equalsIgnoreCase("A")){
                    optA.setSelected(true);
                }
                else if(grade.equalsIgnoreCase("B")){
                    optB.setSelected(true);
                }
                else if(grade.equalsIgnoreCase("C")){
                    optC.setSelected(true);
                }
                job = rs.getString("job");
                cmbJobs.setSelectedItem(job);
                graduate = rs.getString("graduate");
                if(graduate.equalsIgnoreCase("Yes")){
                    chkGraduate.setSelected(true);
                }
                else{
                    if(graduate.equalsIgnoreCase("No")){
                        chkGraduate.setSelected(false);
                    }
                    
                }
                txtSalary.setText(String.valueOf(rs.getFloat("salary")));
                txtCommission.setText(String.valueOf(rs.getFloat("comm")));
            }
            else{
                JOptionPane.showMessageDialog(this, "Employee not found..", "Error!!",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Error!!", JOptionPane.ERROR_MESSAGE);
        }
                
    }//GEN-LAST:event_cmdViewActionPerformed

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        // TODO add your handling code here:
         int empno;
        String ename, grade="", job, graduate;
        float salary = 0.0f, comm = 0.0f;
        try{
            empno = Integer.parseInt(txtEmpNo.getText());
            pst = con.prepareStatement("update employees set ename=?, grade=?, job=?, graduate=?, salary=?, comm=? where empno="+empno);
          
            ename= txtEName.getText();
            if(optA.isSelected()){
                    grade="A";
                }
                else if(optB.isSelected()){
                    grade = "B";
                }
                else if(optC.isSelected()){
                    grade = "C";
                }
            if(chkGraduate.isSelected()){
                graduate = "Yes";
            }
            else{
                graduate = "No";
            }
            job = (String) cmbJobs.getSelectedItem();
            salary = Float.parseFloat(txtSalary.getText());
            comm = Float.parseFloat(txtCommission.getText());
           
            pst.setString(1,ename);
            pst.setString(2, grade);
            pst.setString(3, job);
            pst.setString(4,graduate);
            pst.setFloat(5, salary);
            pst.setFloat(6, comm);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Employee Updated!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Error!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_cmdEditActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        // TODO add your handling code here:
        int empno;
        Statement st1 = null;
        try{
            st1 = con.createStatement();
            empno= Integer.parseInt(txtEmpNo.getText());
            int res=JOptionPane.showConfirmDialog(this, "Confirm to continue deleting...", "Deleting!!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(res == JOptionPane.YES_OPTION ){
                st.executeUpdate("delete from employees where empno="+empno);
                JOptionPane.showMessageDialog(this, "Employee record removed..", "Deleted!!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Error!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_cmdDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkGraduate;
    private javax.swing.JComboBox<String> cmbJobs;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdView;
    private javax.swing.ButtonGroup grp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton optA;
    private javax.swing.JRadioButton optB;
    private javax.swing.JRadioButton optC;
    private javax.swing.JTextField txtCommission;
    private javax.swing.JTextField txtEName;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
